#!/usr/bin/env bash
# #40 exploration: run a probe inside the real Windows Arma client as a
# single-player scenario, unattended, to find out whether `setAccTime` — the
# only real simulation-acceleration lever the engine has — is usable at all
# outside multiplayer, and whether the shim and the Command Port survive the
# move.
#
#   spike/sp-run.sh <probe.sqf> [window-secs]
#
# This is exploration scaffolding, not a tier. It is deliberately crude: no
# lock of its own beyond the tier lock the caller wraps it in, no evidence
# schema, no verdict synthesis beyond grepping the client's RPT for the same
# `CTI|` lines the dedicated server writes to stdout. If the SP route earns a
# place, the tier runner grows it properly; if it does not, this file goes.
#
# Topology, and how it differs from the 2402-2406 tier (ADR-0006):
#   - One process. The Windows client is server, client and (in MP terms) the
#     machine the addon's server-side code runs on, because `isServer` is true
#     in single player. `initServer.sqf` therefore runs and builds the world.
#   - The shim is the cross-compiled .dll in the game root, not the .so.
#   - The daemon still runs in WSL2. The shim's `addr` command points it at the
#     WSL LAN address; mirrored networking's loopback across the boundary is not
#     something this script assumes.
#   - No ports in 2402-2406 are used at all: single player opens no game socket.
#     The daemon port is the only shared resource, which is why this still runs
#     under the tier lock.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROBE="${1:?usage: sp-run.sh <probe.sqf> [window-secs]}"
WINDOW="${2:-300}"
MISSION="${CTI_MISSION:-cti.Stratis}"
DAEMON_PORT="${CTI_DAEMON_PORT:-9099}"
ARMA_DIR="${CTI_WINDOWS_ARMA_DIR:-/mnt/d/Apps/Steam/steamapps/common/Arma 3}"
ARMA_WIN="${CTI_WINDOWS_ARMA_WINPATH:-D:\\Apps\\Steam\\steamapps\\common\\Arma 3}"

OUT="$HOME/.arma-cti/runs/$(date -u +%Y%m%dT%H%M%SZ)-sp-$(basename "$PROBE" .sqf)"
mkdir -p "$OUT"
log() { printf '[sp] %s\n' "$*" >&2; }
fail() {
    printf 'verdict=FAIL\nfailure_class=%s\nfailure_detail=%s\n' "$1" "$2" >>"$OUT/results.env"
    log "FAILED: $1 — $2"
    exit 1
}

[[ -f "$PROBE" ]] || fail infra_unavailable "no such probe: $PROBE"
[[ -f "$ARMA_DIR/arma3_x64.exe" ]] || fail infra_unavailable "no Windows client at $ARMA_DIR"

# The client is the human's machine. A running one is theirs, and the answer is
# stop, not kill.
#
# Resolved by absolute path, not by name: the interop binaries are not on this
# environment's PATH, and `command -v tasklist.exe` is therefore false here.
# A check that cannot run is not a check that passed, so a missing tool refuses
# the run — which is the difference between this and spike/regress.sh's version
# of the same guard (#41).
TASKLIST="${CTI_WINDOWS_TASKLIST:-/mnt/c/Windows/System32/tasklist.exe}"
TASKKILL="${CTI_WINDOWS_TASKKILL:-/mnt/c/Windows/System32/taskkill.exe}"
[[ -x "$TASKLIST" ]] || fail infra_unavailable "cannot see the Windows process list at $TASKLIST; refusing to take a machine I cannot check"
if "$TASKLIST" /FI "IMAGENAME eq arma3_x64.exe" 2>/dev/null | grep -qi arma3_x64.exe; then
    fail infra_unavailable "arma3_x64.exe already running — that is a play session, not ours"
fi

DLL="$REPO/extension/target/x86_64-pc-windows-msvc/release/cti_shim.dll"
[[ -f "$DLL" ]] || fail infra_unavailable "shim .dll not built (just build-shim-windows)"
BUILT_MOD="$REPO/.hemttout/build"
[[ -d "$BUILT_MOD/addons" ]] || fail infra_unavailable "addon not built (just build-addon)"

# ------------------------------------------------------------------- staging
# The engine appends _x64 to the name SQF asks for, exactly as on Linux.
install -m 0755 "$DLL" "$ARMA_DIR/cti_shim_x64.dll" || fail infra_unavailable "cannot stage the shim"
rm -rf "${ARMA_DIR:?}/@cti"
mkdir -p "$ARMA_DIR/@cti"
cp -r "$BUILT_MOD/addons" "$ARMA_DIR/@cti/"

# The WSL side's LAN address, because the daemon lives there and the client does
# not. Both candidates are written; the probe tries them in order.
LAN_IP="$(ip -4 -o addr show scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 |
    grep -E '^192\.168\.' | head -1)"

# The mission stays inside the game directory, which is where the engine
# demonstrably loads one from. The autotest config and the profile do not: the
# engine cannot open an `-autotest=` path containing a space, however it is
# quoted (measured — "Cannot open AutoTest config file" against the game
# directory's own path, which contains "Arma 3"), so both live under a spaceless
# staging root.
AUTOTEST="$ARMA_DIR/autotest"
STAGE="${CTI_SP_STAGE:-/mnt/c/arma-cti-sp}"
STAGE_WIN="${CTI_SP_STAGE_WINPATH:-C:\\arma-cti-sp}"
rm -rf "${AUTOTEST:?}" "${STAGE:?}"
mkdir -p "$AUTOTEST/$MISSION" "$STAGE/profile"
cp -r "$REPO/missions/$MISSION/." "$AUTOTEST/$MISSION/"
{
    echo "// Generated by spike/sp-run.sh. Do not edit."
    printf 'CTI_DESYNC_WATCH_SECS = 0;\nCTI_DESYNC_LOAD = 0;\nCTI_PROBE_SOAK = 0;\n'
    # In single player the shim has to be told where the daemon is: its default
    # 127.0.0.1 is the Windows host's loopback and the daemon is in the VM.
    # Inline rather than in a `daemon_addrs.sqf` beside the mission, because
    # cti.Stratis has no init.sqf to load one — spike.Stratis did, and copying
    # that shape here cost a run to discover.
    printf 'CTI_SPIKE_DAEMON_ADDRS = ["127.0.0.1:%s"' "$DAEMON_PORT"
    [[ -n "$LAN_IP" ]] && printf ', "%s:%s"' "$LAN_IP" "$DAEMON_PORT"
    printf '];\n'
    printf 'CTI_SP_ACCTIME = %s;\n' "${CTI_SP_ACCTIME:-1}"
    cat <<'SQF'
[] spawn {
    private _shim = call cti_fnc_shimName;
    diag_log format ["CTI|sp_topology shim=%1 isServer=%2 isMP=%3 hasInterface=%4 version=%5",
        _shim, isServer, isMultiplayer, hasInterface, productVersion];
    if (_shim isEqualTo "") exitWith { diag_log "CTI|FAIL class=infra_unavailable sp_no_shim"; };
    {
        private _reply = (_shim callExtension ["addr", [_x]]) # 0;
        private _ping = (_shim callExtension ["rpc_keepalive", [toJSON createHashMapFromArray [
            ["id", "sp-reach"], ["verb", "observe"],
            ["payload", createHashMapFromArray [
                ["time", time], ["presence", call cti_fnc_presenceSample]
            ]]
        ]]]) # 0;
        diag_log format ["CTI|sp_daemon_probe addr=%1 set=%2 reply=%3", _x, _reply, _ping];
        // Reachability is about the transport, not about whether the daemon
        // liked the request: a rejection is a daemon that answered. Only the
        // shim's own `connect:` failure means nothing is listening.
        if (_ping != "" && { (_ping find "connect:") < 0 }) exitWith {
            diag_log format ["CTI|sp_daemon_reachable addr=%1", _x];
        };
    } forEach CTI_SPIKE_DAEMON_ADDRS;

    // Acceleration goes on after the daemon is reachable, so the address search
    // above is not itself measured at a different rate than a 1x control run.
    if (CTI_SP_ACCTIME != 1) then {
        setAccTime CTI_SP_ACCTIME;
        diag_log format ["CTI|sp_acctime requested=%1 accTime=%2", CTI_SP_ACCTIME, accTime];
    };
};
SQF
} >"$AUTOTEST/$MISSION/harness.sqf"
cat "$PROBE" >>"$AUTOTEST/$MISSION/harness.sqf"
cp "$AUTOTEST/$MISSION/harness.sqf" "$OUT/harness.sqf"

cat >"$STAGE/autotest.cfg" <<EOF
class TestMissions
{
	class CtiProbe
	{
		campaign = "";
		mission = "$ARMA_WIN\\autotest\\$MISSION";
	};
};
EOF

# -------------------------------------------------------------------- daemon
DAEMON_LOG="$OUT/daemon.log"
(cd "$REPO" && exec uv run --quiet cti-daemon \
    --host 0.0.0.0 --port "$DAEMON_PORT" \
    --telemetry "$OUT/daemon-telemetry.jsonl") >"$DAEMON_LOG" 2>&1 &
daemon_pid=$!
for _ in $(seq 1 90); do
    grep -q CTI_DAEMON_READY "$DAEMON_LOG" && break
    sleep 1
done
grep -q CTI_DAEMON_READY "$DAEMON_LOG" || fail infra_unavailable "daemon never reported ready; see $DAEMON_LOG"

cleanup() {
    "$TASKKILL" /IM arma3_x64.exe /F >/dev/null 2>&1
    [[ -n "${daemon_pid:-}" ]] && kill "$daemon_pid" 2>/dev/null
}
trap cleanup EXIT

# -------------------------------------------------------------------- client
CLIENT_LOG="$OUT/client.stdout.log"
log "launching the client (window ${WINDOW}s)"
(
    cd "$ARMA_DIR" || exit 1
    exec ./arma3_x64.exe \
        -autotest="$STAGE_WIN\\autotest.cfg" \
        -profiles="$STAGE_WIN\\profile" \
        -mod=@cti \
        -filePatching \
        -window \
        -noSplash \
        -skipIntro \
        -noPause \
        -noSound \
        -world=empty
) >"$CLIENT_LOG" 2>&1 &
client_pid=$!

# The client's RPT is this run's server-stdout equivalent: -profiles puts it
# somewhere we chose rather than in the human's AppData.
RPT=""
deadline=$((SECONDS + WINDOW))
while ((SECONDS < deadline)); do
    if [[ -z "$RPT" ]]; then
        RPT="$(find "$STAGE/profile" -name '*.rpt' -newermt '-10 minutes' 2>/dev/null | head -1)"
        [[ -n "$RPT" ]] && log "rpt: $RPT"
    elif grep -q 'probe_done' "$RPT" 2>/dev/null; then
        log "probe finished"
        break
    fi
    kill -0 "$client_pid" 2>/dev/null || {
        log "client exited"
        break
    }
    sleep 2
done

[[ -n "$RPT" ]] && cp "$RPT" "$OUT/client.rpt"
grep -o 'CTI|[^"]*' "$OUT/client.rpt" 2>/dev/null | tee "$OUT/cti-lines.log" >&2

if [[ ! -f "$OUT/client.rpt" ]]; then
    fail infra_unavailable "the client wrote no RPT under $STAGE/profile; see $CLIENT_LOG"
fi
if ! grep -q 'probe_done' "$OUT/client.rpt"; then
    fail timeout "no probe_done in ${WINDOW}s; evidence in $OUT"
fi
if grep -q 'CTI|FAIL' "$OUT/client.rpt"; then
    class="$(grep -o 'CTI|FAIL class=[a-z_]*' "$OUT/client.rpt" | head -1 | sed 's/.*class=//')"
    fail "${class:-assertion_failed}" "probe reported a failure; evidence in $OUT"
fi
printf 'verdict=PASS\n' >>"$OUT/results.env"
log "PASS — evidence in $OUT"
