"""Split MediaWiki XML exports of the Bohemia wiki into one wikitext file per page.

The Bohemia Interactive Community wiki (BIKI) is the primary source for almost
every engine fact this project depends on, and it sits behind Cloudflare —
direct fetches, the MediaWiki API and even a browser user-agent all return 403
from here. Arma 3 has meanwhile been static at 2.20 for over a year, so a
vendored snapshot is both necessary and cheap to keep current.

Point this at a directory of `action=query&generator=allpages&export=1` chunks
(see `docs/reference/arma-wiki/INDEX.md` for how one is produced). Each page
becomes `<bucket>/<slug>.wiki` carrying a provenance header — title, source URL,
revision id, revision timestamp, the export's own sha1 and the page's categories
— so a stale page is detectable without re-fetching.

Two facts about BIKI drive the shape of the output:

- Category assignment is generated by templates, not written into page source,
  so relevance cannot be determined by grepping the wikitext. It comes from a
  separate `categories.json` pulled from `prop=categories`, and `--manifest`
  applies the tier decision derived from it.
- Roughly a quarter of pages are redirect stubs. Writing 2,600 one-line files
  buys nothing, so redirects are recorded as an alias map in `MANIFEST.json`
  instead.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

WIKI_BASE = "https://community.bistudio.com/wiki/"

# Namespace id -> (output directory, title prefix to strip). The bucket
# directory already says which namespace a page came from, so repeating the
# prefix in every filename is noise.
NAMESPACES = {
    4: ("meta", "Bohemia Interactive Community:"),
    10: ("templates", "Template:"),
    12: ("meta", "Help:"),
    14: ("categories", "Category:"),
    102: ("meta", "Extension:"),
}

# ns0 bucketing, first match wins. Class-name and asset tables are split out
# from prose because they are enormous (43 pages hold more than half the
# snapshot's bytes) and are looked up, not read.
BULK_DATA_TITLE = re.compile(
    r"Cfg(Vehicles|Weapons|Magazines|Patches|Sounds|Ammo|Groups)"
    r"|classNames|Class Names|Sound Files|: Moves\b|/vehicles\b|/objects\b"
)
COMMAND_CATEGORY = re.compile(r"Scripting Commands")
FUNCTION_CATEGORY = re.compile(r"Scripting Functions|: Functions\b")

# BIKI titles operators as prose ("a greater= b"), and a naive slug collapses
# nine distinct operator pages onto one filename. Symbol tokens therefore map to
# words. Longest match first, so "==" never decomposes into two "=".
STANDALONE_OPERATORS = {
    "&&": "and",
    "||": "or",
    "==": "eq",
    "!=": "ne",
    ">=": "ge",
    "<=": "le",
    "+=": "plus_eq",
    "-=": "minus_eq",
    "*=": "star_eq",
    "/=": "div_eq",
    "%": "mod",
    "&": "and",
    "|": "or",
    "!": "not",
    "=": "assign",  # standalone "=" is assignment; "==" above is equality
    "+": "plus",
    "-": "minus",
    "*": "star",
    "/": "div",
    ":": "colon",
    "^": "pow",
    "<": "lt",
    ">": "gt",
}
# Applied inside a token that also carries letters, e.g. "Array+=" or
# "a greater= b". ":" and "/" are excluded: there they are structural (title
# namespace separators and subpage separators), not arithmetic.
EMBEDDED_OPERATORS = {
    "+=": "_plus_eq_",
    "-=": "_minus_eq_",
    "==": "_eq_",
    "!=": "_ne_",
    ">=": "_ge_",
    "<=": "_le_",
    "&&": "_and_",
    "||": "_or_",
    "=": "_eq_",
    "+": "_plus_",
    "%": "_mod_",
    "^": "_pow_",
    "<": "_lt_",
    ">": "_gt_",
}
_SYMBOLS_ONLY = re.compile(r"^[!-/:-@\[-`{-~]+$")


@dataclass(frozen=True)
class Page:
    """One exported wiki page plus the provenance needed to spot a stale copy."""

    title: str
    namespace: int
    text: str
    revision_id: str
    timestamp: str
    sha1: str
    redirect_target: str | None = None
    categories: tuple[str, ...] = ()

    @property
    def is_redirect(self) -> bool:
        """Whether this page is a redirect stub rather than content."""
        return self.redirect_target is not None

    @property
    def slug(self) -> str:
        """Filesystem-safe stem, so `Arma 3: Named Pipe` becomes `Arma_3_Named_Pipe`."""
        _, prefix = NAMESPACES.get(self.namespace, ("", ""))
        title = self.title.removeprefix(prefix) if prefix else self.title
        return slugify(title)

    @property
    def bucket(self) -> str:
        """Output subdirectory: namespace for non-articles, subject matter for ns0."""
        if self.namespace in NAMESPACES:
            return NAMESPACES[self.namespace][0]
        if BULK_DATA_TITLE.search(self.title):
            return "classnames"
        categories = " | ".join(self.categories)
        if COMMAND_CATEGORY.search(categories):
            return "commands"
        if FUNCTION_CATEGORY.search(categories):
            return "functions"
        return "topics"

    @property
    def url(self) -> str:
        """Canonical wiki URL for this page."""
        return WIKI_BASE + self.title.replace(" ", "_")

    def render(self) -> str:
        """Render the vendored file: provenance header, then the wikitext verbatim."""
        header = [
            f"// source: {self.url}",
            f"// revision: {self.revision_id} ({self.timestamp})",
            f"// export sha1: {self.sha1}",
        ]
        if self.categories:
            # Categories live in templates, not page source, so without this line
            # there is no way to tell from the file which games a page applies to.
            header.append(f"// categories: {' | '.join(self.categories)}")
        header.append("// Vendored snapshot. Do not edit — re-export instead.")
        return "\n".join(header) + f"\n\n{self.text.rstrip()}\n"


def _map_symbol_token(token: str) -> str:
    """Rewrite an all-punctuation token such as `!=` or `/` into words."""
    words: list[str] = []
    index = 0
    while index < len(token):
        for symbol, word in STANDALONE_OPERATORS.items():
            if token.startswith(symbol, index):
                words.append(word)
                index += len(symbol)
                break
        else:
            words.append("sym")
            index += 1
    return "_".join(words)


def slugify(title: str) -> str:
    """Turn a wiki title into a filename stem, keeping operator pages distinct."""
    tokens: list[str] = []
    for raw in title.split():
        if _SYMBOLS_ONLY.match(raw):
            tokens.append(_map_symbol_token(raw))
            continue
        token = raw
        for symbol, word in EMBEDDED_OPERATORS.items():
            token = token.replace(symbol, word)
        tokens.append(token)
    return re.sub(r"[^A-Za-z0-9]+", "_", "_".join(tokens)).strip("_")


def _child_text(element: ET.Element, uri: str, tag: str) -> str:
    found = element.find(f"{{{uri}}}{tag}")
    return "" if found is None or found.text is None else found.text


def parse_export(xml: str, categories: dict[str, list[str]] | None = None) -> list[Page]:
    """Read every page out of a MediaWiki export, newest revision only."""
    root = ET.fromstring(xml)  # noqa: S314 - trusted local export
    match = re.match(r"\{(.*)\}", root.tag)
    if match is None:
        msg = "not a MediaWiki export: root element carries no namespace"
        raise ValueError(msg)
    uri = match.group(1)

    pages: list[Page] = []
    for element in root.findall(f"{{{uri}}}page"):
        revision = element.find(f"{{{uri}}}revision")
        if revision is None:
            continue
        title = _child_text(element, uri, "title")
        redirect = element.find(f"{{{uri}}}redirect")
        pages.append(
            Page(
                title=title,
                namespace=int(_child_text(element, uri, "ns") or "0"),
                text=_child_text(revision, uri, "text"),
                revision_id=_child_text(revision, uri, "id"),
                timestamp=_child_text(revision, uri, "timestamp"),
                sha1=_child_text(revision, uri, "sha1"),
                redirect_target=None if redirect is None else redirect.get("title", ""),
                categories=tuple((categories or {}).get(title, ())),
            )
        )
    if not pages:
        msg = "export contains no pages"
        raise ValueError(msg)
    return pages


def load_categories(path: Path | None) -> dict[str, list[str]]:
    """Read the `prop=categories` sidecar: page title -> category names."""
    if path is None:
        return {}
    raw = json.loads(path.read_text(encoding="utf-8"))
    return {title: entry.get("categories", []) for title, entry in raw.items()}


def load_tiers(path: Path | None) -> dict[str, str]:
    """Read the relevance manifest: main-namespace page title -> tier letter."""
    if path is None:
        return {}
    raw = json.loads(path.read_text(encoding="utf-8"))
    return {title: entry["tier"] for title, entry in raw.get("pages", {}).items()}


def select(pages: list[Page], tiers: dict[str, str], keep: set[str]) -> list[Page]:
    """Drop main-namespace pages outside the wanted tiers; keep other namespaces whole.

    A page with no tier entry is kept, so an export taken without the manifest
    sidecar still round-trips rather than silently vanishing.
    """
    return [
        page
        for page in pages
        if page.namespace != 0 or tiers.get(page.title) in keep or page.title not in tiers
    ]


def assign_paths(pages: list[Page]) -> dict[str, str]:
    """Map each page title to its output path, breaking case-insensitive clashes.

    Case-folded uniqueness matters even though this repo lives on ext4: a
    checkout on Windows or macOS would otherwise silently overwrite one page
    with another. Clashes resolve by title order and are recorded in the
    manifest, so the mapping is reproducible rather than incidental.
    """
    taken: set[tuple[str, str]] = set()
    paths: dict[str, str] = {}
    for page in sorted(pages, key=lambda p: (p.bucket, p.title)):
        stem = page.slug or "untitled"
        candidate, suffix = stem, 1
        while (page.bucket, candidate.lower()) in taken:
            suffix += 1
            candidate = f"{stem}~{suffix}"
        taken.add((page.bucket, candidate.lower()))
        paths[page.title] = f"{page.bucket}/{candidate}.wiki"
    return paths


def build_manifest(
    pages: list[Page],
    redirects: list[Page],
    paths: dict[str, str],
    provenance: dict[str, object],
) -> str:
    """Render MANIFEST.json: the authoritative title-to-file lookup plus aliases."""
    manifest = {
        "provenance": provenance,
        "pages": {
            page.title: {
                "path": paths[page.title],
                "ns": page.namespace,
                "revision": page.revision_id,
                "timestamp": page.timestamp,
                "sha1": page.sha1,
                "bytes": len(page.text.encode()),
            }
            for page in sorted(pages, key=lambda p: p.title)
        },
        # Redirect stubs are not written as files; this alias map replaces them,
        # so "setdamage" still resolves to the setDamage page.
        "redirects": {
            page.title: page.redirect_target
            for page in sorted(redirects, key=lambda p: p.title)
            if page.redirect_target
        },
    }
    return json.dumps(manifest, indent=1, ensure_ascii=False) + "\n"


def build_bucket_index(bucket: str, pages: list[Page], paths: dict[str, str]) -> str:
    """Render a browsable per-bucket listing of titles and their files."""
    lines = [
        f"# {bucket} ({len(pages)} pages)",
        "",
        "Part of the vendored BIKI snapshot. See ../INDEX.md for provenance and",
        "refresh instructions. Do not edit these files — re-export instead.",
        "",
        "| Page | Last edited |",
        "|---|---|",
    ]
    lines.extend(
        f"| [{page.title}]({Path(paths[page.title]).name}) | {page.timestamp[:10]} |"
        for page in sorted(pages, key=lambda p: p.title)
    )
    lines.append("")
    return "\n".join(lines)


BUCKET_DESCRIPTIONS = {
    "commands": "SQF scripting commands, one page per command",
    "functions": "BIS functions (`BIS_fnc_*`) and other library functions",
    "topics": "Prose: engine topics, tutorials, config and editor reference",
    "classnames": "Bulk class-name and asset tables. Large; look up, do not read",
    "templates": "Wiki templates. Needed to interpret `{{RV}}` markup in page source",
    "categories": "Category description pages, not membership lists",
    "meta": "Wiki policy, help and extension pages",
}


def build_index(
    buckets: dict[str, list[Page]],
    redirects: list[Page],
    tiers: dict[str, int],
    snapshot: str = "",
) -> str:
    """Render the INDEX.md that fronts the whole snapshot."""
    total = sum(len(pages) for pages in buckets.values())
    payload = sum(len(page.text.encode()) for pages in buckets.values() for page in pages)
    tier_a, tier_b = tiers.get("A", 0), tiers.get("B", 0)
    lines = [
        "# Arma 3 wiki snapshot",
        "",
        "Vendored from the Bohemia Interactive Community wiki (BIKI), which is",
        "unreachable from this project's environment: Cloudflare returns 403 to plain",
        "fetches, to the MediaWiki API and to browser-like requests alike. Arma 3 has",
        "been static at 2.20 since June 2025, so these pages change rarely.",
        "",
        "Content belongs to Bohemia Interactive and its wiki contributors. This is a",
        "verbatim snapshot for offline reference, not project documentation — cite the",
        "source URL in each file's header, never this directory.",
        "",
        "## What is here",
        "",
        f"{total} pages, {payload / 1e6:.1f} MB of wikitext"
        + (f", taken {snapshot}." if snapshot else "."),
        "",
        "| Directory | Pages | Contents |",
        "|---|---|---|",
    ]
    lines.extend(
        f"| [`{bucket}/`]({bucket}/INDEX.md) | {len(buckets[bucket])} "
        f"| {BUCKET_DESCRIPTIONS[bucket]} |"
        for bucket in sorted(buckets)
    )
    lines.extend(
        [
            "",
            "## Finding a page",
            "",
            "Paths are predictable: a scripting command lives at `commands/<name>.wiki`,",
            "so `setDamage` is `commands/setDamage.wiki`. Titles carrying punctuation are",
            "slugged — `:` and `/` become `_`, and operator pages spell their symbols out,",
            "so `a != b` is `commands/a_ne_b.wiki`. Each directory has its own INDEX.md",
            "listing every page it holds.",
            "",
            "`MANIFEST.json` is the authoritative lookup. It maps every title to its path,",
            "revision, timestamp and sha1, and carries the redirect alias map",
            f"({len(redirects)} aliases): redirect stubs are not written as files, so an",
            "alternate spelling such as `AGLtoASL` resolves to the `AGLToASL` page through",
            "the manifest rather than through a one-line file. Aliases whose target this",
            "snapshot excludes are dropped, so every alias resolves to a file that exists.",
            "",
            "## Scope",
            "",
            "The snapshot covers the main, template, category, help, project and extension",
            "namespaces. Within the main namespace it keeps two tiers:",
            "",
            "| Tier | Rule | Pages |",
            "|---|---|---|",
            f"| A | Carries an `Arma 3` or `Introduced with Arma 3` category | {tier_a} |",
            f"| B | Carries no game-specific category: engine-generic or shared | {tier_b} |",
            "",
            "Pages categorised only for earlier titles (Operation Flashpoint, ArmA, Arma 2,",
            "Take On) or for other engines (Reforger, Arma 4, DayZ, Enfusion) are excluded,",
            "as are File-namespace content, talk pages and edit history.",
            "",
            "## Important: categories are not in the wikitext",
            "",
            "BIKI generates category assignment from templates, so page source contains no",
            "`[[Category:...]]` links and you cannot tell from the wikitext which games a",
            "page applies to. Applicability is encoded as `{{RV}}` parameters (`game6=",
            "arma3`). Each vendored file therefore carries a `// categories:` header line,",
            "pulled from the API's `prop=categories` at snapshot time and stamped in at",
            "import — so `grep -l 'Arma 3: Scripting Commands' commands/*.wiki` works,",
            "where grepping the wikitext itself would find nothing.",
            "",
            "## Refreshing",
            "",
            "Cloudflare challenges plain HTTP clients, so the export is produced by driving",
            "the MediaWiki API from a logged-in browser session, which inherits the",
            "browser's TLS fingerprint and clearance cookie:",
            "",
            "```",
            "/wikidata/api.php?action=query&generator=allpages&export=1&gaplimit=500",
            "```",
            "",
            "Then re-derive this directory from the resulting chunks:",
            "",
            "```sh",
            "uv run python tools/import_wiki_export.py <export-dir> docs/reference/arma-wiki \\",
            "    --categories <export-dir>/categories.json \\",
            "    --manifest <export-dir>/arma3-manifest.json",
            "```",
            "",
            "The tool is idempotent: it rewrites every page, index and manifest from the",
            "export, so a refresh reads as a clean diff rather than a merge.",
            "",
        ]
    )
    return "\n".join(lines)


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("export", type=Path, help="MediaWiki export XML, or a directory of them")
    parser.add_argument("output", type=Path, help="directory to write pages into")
    parser.add_argument("--categories", type=Path, help="categories.json from prop=categories")
    parser.add_argument("--manifest", type=Path, help="arma3-manifest.json carrying tier decisions")
    parser.add_argument("--snapshot", default="", help="ISO timestamp the export was taken at")
    parser.add_argument(
        "--tier",
        action="append",
        default=None,
        help="main-namespace tier to keep; repeatable. Defaults to A and B.",
    )
    parser.add_argument(
        "--expect",
        action="append",
        default=[],
        help="page title that must be present; repeatable. Missing titles are an error, "
        "because an export silently omits a page it could not resolve.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Split `export` into one file per page under `output`."""
    args = _parse_args(argv)

    sources = sorted(args.export.glob("*.xml")) if args.export.is_dir() else [args.export]
    if not sources:
        print(f"no XML files under {args.export}", file=sys.stderr)  # noqa: T201
        return 1

    categories = load_categories(args.categories)
    pages = [
        page
        for source in sources
        for page in parse_export(source.read_text(encoding="utf-8"), categories)
    ]

    missing = sorted(set(args.expect) - {page.title for page in pages})
    if missing:
        print(f"missing from export: {', '.join(missing)}", file=sys.stderr)  # noqa: T201
        return 1

    tiers = load_tiers(args.manifest)
    kept = select(pages, tiers, set(args.tier or ["A", "B"]))
    content = [page for page in kept if not page.is_redirect]
    paths = assign_paths(content)
    # An alias pointing at a page this snapshot excluded is worse than no alias:
    # it sends a reader to a file that is not there. Roughly half of BIKI's
    # redirects target pre-Arma-3 or user pages, so drop those.
    redirects = [page for page in kept if page.is_redirect and page.redirect_target in paths]

    buckets: dict[str, list[Page]] = defaultdict(list)
    tier_counts: dict[str, int] = defaultdict(int)
    for page in content:
        buckets[page.bucket].append(page)
        if page.namespace == 0:
            tier_counts[tiers.get(page.title, "?")] += 1

    args.output.mkdir(parents=True, exist_ok=True)
    for page in content:
        target = args.output / paths[page.title]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(page.render(), encoding="utf-8")
    for bucket, bucket_pages in buckets.items():
        (args.output / bucket / "INDEX.md").write_text(
            build_bucket_index(bucket, bucket_pages, paths), encoding="utf-8"
        )

    provenance = {
        "source": WIKI_BASE,
        "snapshot": args.snapshot,
        "pages": len(content),
        "redirects": len(redirects),
        "chunks": [source.name for source in sources],
    }
    (args.output / "MANIFEST.json").write_text(
        build_manifest(content, redirects, paths, provenance), encoding="utf-8"
    )
    (args.output / "INDEX.md").write_text(
        build_index(dict(buckets), redirects, dict(tier_counts), args.snapshot), encoding="utf-8"
    )

    print(f"{len(content)} pages, {len(redirects)} redirect aliases -> {args.output}")  # noqa: T201
    return 0


if __name__ == "__main__":
    sys.exit(main())
